spring:
#  sql:
#    init:
#      mode: always
  application:
    name: equitycart
  datasource:
    url: jdbc:postgresql://localhost:5432/equitycart
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://localhost:27017/equitycart


server:
  port: 8080

jwt:
  secret: dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGVxdWl0eWNhcnQgand0IHRva2Vu  # base64 of a 256-bit key
  access-token-expiry: 900000    # 15 minutes in milliseconds
  refresh-token-expiry: 7  # 7 days in days