package com.equitycart.commons.config;

import com.equitycart.commons.filter.JwtAuthenticationFilter;
import com.equitycart.commons.security.api.JwtTokenValidator;
import lombok.RequiredArgsConstructor;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;

/**
 * Spring Security auto-configuration for per-service JWT validation.
 *
 * <p><b>Conditional Activation:</b> This configuration only applies if the property {@code
 * equitycart.security.enabled=true} is set in application.yml or via environment variable. This
 * prevents unintended security auto-wiring in infrastructure services (e.g., discovery-server,
 * config-server) that should not enforce authentication.
 *
 * <p><b>What It Configures:</b>
 *
 * <ul>
 *   <li>CSRF protection: disabled (stateless API, no session-based CSRF risk)
 *   <li>Session management: STATELESS (no HttpSession created, each request validated
 *       independently)
 *   <li>Filter chain: JwtAuthenticationFilter inserted BEFORE UsernamePasswordAuthenticationFilter
 *   <li>Authorization rules:
 *       <ul>
 *         <li>"/api/auth/**" (login, register, refresh): permitAll (public endpoints)
 *         <li>"/actuator/**" (health, metrics): permitAll (infrastructure queries)
 *         <li>anyRequest: authenticated (all other endpoints require valid JWT)
 *       </ul>
 *   <li>Method-level security: @EnableMethodSecurity activates @PreAuthorize annotations for
 *       role-based access control
 * </ul>
 *
 * <p><b>Critical Constraint — {@code anyRequest()} is terminal:</b> In Spring Security's {@code
 * AuthorizeHttpRequestsConfigurer}, calling {@code anyRequest()} registers a catch-all matcher.
 * Once registered, NO further matchers can be added — a second {@code anyRequest()} or any
 * subsequent {@code requestMatchers()} call throws {@code IllegalStateException} ("Can't configure
 * anyRequest after itself"). This means the authorization chain must be:
 *
 * <pre>
 *   specific matchers first → anyRequest() LAST
 * </pre>
 *
 * An earlier broken version attempted separate chains (e.g., {@code
 * anyRequest().hasRole("SERVICE")} then another {@code anyRequest().authenticated()}) which
 * silently failed — only the first applied. The fix: a single {@code anyRequest().authenticated()}
 * that accepts ANY valid JWT (user or service) while role-specific restrictions use
 * {@code @PreAuthorize} at method level.
 *
 * <p><b>How ServiceTokenProvider tokens pass:</b> Tokens generated by {@code
 * ServiceTokenProviderImpl} (subject=0, role=SERVICE) satisfy {@code .authenticated()} because they
 * are valid JWTs — the {@code JwtAuthenticationFilter} extracts the principal and sets a non-null
 * {@code Authentication} in {@code SecurityContextHolder}. Role-based restrictions (CUSTOMER,
 * SELLER) are enforced via {@code @PreAuthorize} on specific controller methods, which SERVICE
 * tokens intentionally do not satisfy — service-to-service calls only access endpoints that require
 * authentication without role constraints.
 *
 * <p><b>Pattern:</b> Spring Boot auto-configuration idiom. Instead of each service copying
 * SecurityConfig, they inherit this bean transitively (via commons dependency). A service can
 * override this by defining its own @Configuration with different rules.
 *
 * <p><b>Activation Example:</b> In order-service/equitycart-config/order-service.yml:
 *
 * <pre>
 *   equitycart:
 *     security:
 *       enabled: true
 * </pre>
 *
 * <p><b>Thread Safety:</b> SecurityFilterChain and HttpSecurity are built during Spring's bootstrap
 * phase (synchronized). At runtime, the filter chain handles concurrent requests safely
 * (SecurityContextHolder is thread-local).
 *
 * @see com.equitycart.commons.filter.JwtAuthenticationFilter
 * @see com.equitycart.commons.security.api.JwtTokenValidator
 */
@Configuration
@RequiredArgsConstructor
@EnableMethodSecurity
@ConditionalOnProperty(name = "equitycart.security.mode", havingValue = "custom")
public class SecurityAutoConfig {

  private static final Logger log = LogManager.getLogger(SecurityAutoConfig.class);

  //  private final JwtAuthenticationFilter jwtAuthenticationFilter;
  private final JwtTokenValidator jwtTokenValidator;

  /**
   * Builds the Spring Security filter chain for stateless JWT-based authentication.
   *
   * <p>This bean is only created if equitycart.security.mode=custom.
   *
   * @param httpSecurity the HttpSecurity builder (injected by Spring)
   * @return configured SecurityFilterChain
   * @throws Exception if configuration fails (deferred by Spring to startup diagnostics)
   */
  @Bean
  public SecurityFilterChain securityFilterChain(HttpSecurity httpSecurity) throws Exception {
    log.info("Enabling JWT-based security auto-configuration; registering JwtAuthenticationFilter");
    return httpSecurity
        .csrf(AbstractHttpConfigurer::disable)
        .sessionManagement(se -> se.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
        .addFilterBefore(
            new JwtAuthenticationFilter(jwtTokenValidator),
            UsernamePasswordAuthenticationFilter.class)
        .authorizeHttpRequests(
            auth ->
                auth.requestMatchers("/api/auth/**", "/actuator/**")
                    .permitAll()
                    .anyRequest()
                    .authenticated())
        .build();
  }
}
