plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

dependencies {
    implementation 'org.springframework.cloud:spring-cloud-config-server'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
}
bootJar {
    archiveBaseName.set('config-server')
    archiveVersion.set(project.version.toString())
    archiveClassifier.set('exec')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}