services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    ports:
      - 9432:5432 # Host:9432 → Container:5432 (9432 avoids conflict with org's local PostgreSQL on 5432)
    environment:
      - POSTGRES_DB=equitycart
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    #      - POSTGRES_MULTIPLE_DATABASES="equitycart",equitycart_ledger","equitycart_notification","equitycart_order","equitycart_product","equitycart_user","equitycart_portfolio"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    networks:
      - equitycart_network
  kafka:
    container_name: kafka
    image: apache/kafka:latest
    user: "0" #← add this line (runs Kafka process as root inside container)
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,DOCKER://:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,DOCKER://kafka:29092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
      - KAFKA_LOG_DIRS=/var/kafka/data
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    volumes:
      - kafka-data:/var/kafka/data
    networks:
      - equitycart_network

  debezium:
    container_name: debezium
    depends_on:
      - postgres
      - kafka
    image: debezium/connect:2.5
    ports:
      - 8083:8083
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=equitycart-connect
      - CONFIG_STORAGE_TOPIC=equitycart-connect-configs
      - OFFSET_STORAGE_TOPIC=equitycart-connect-offsets
      - STATUS_STORAGE_TOPIC=equitycart-connect-status
    networks:
      - equitycart_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - equitycart_network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - equitycart_network

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - equitycart_network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev --import-realm
    depends_on:
      - postgres
    ports:
      - 8180:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_HEALTH_ENABLED=true
    networks:
      - equitycart_network
    volumes:
      - ./keycloak/equitycart-realm.json:/opt/keycloak/data/import/equitycart-realm.json:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - equitycart_network
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    networks:
      - equitycart_network
    depends_on:
      - prometheus

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - equitycart_network

## Commented out for now, as ElasticSearch and Kibana are not currently used in the project as environment-constrained, blocked by Zscaler

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#      - ES_JAVA_OPTS=-Xms1g -Xmx1g
#    ports:
#      - "9200:9200"
#    volumes:
#      - elasticsearch-data:/usr/share/elasticsearch/data
#    networks:
#      - equitycart_network

#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.14.3
#    container_name: kibana
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#    networks:
#      - equitycart_network
#
#  fluentd:
#    build:
#      context: ./fluentd
#      dockerfile: Dockerfile
#    container_name: fluentd
#    volumes:
#      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf:ro
#      - ./logs:/logs:ro
#    depends_on:
#      - elasticsearch
#    networks:
#      - equitycart_network

volumes:
  postgres-data:
  kafka-data:
  redis-data:
  mongo-data:
  prometheus_data:
  grafana-data:
#  elasticsearch-data:

networks:
  equitycart_network:
    external: true
    name: equitycart_network