# Read all service JSON logs
<source>
  @type tail
  path /logs/*/*.log
  pos_file /fluentd/log/fluentd.pos
  tag equitycart.logs
  read_from_head true
  <parse>
    @type json
  </parse>
</source>

# Keep/flatten useful IDs for easier Kibana querying
<filter equitycart.logs>
  @type record_transformer
  enable_ruby true
  <record>
    correlationId ${record.dig("contextMap","correlationId")}
    traceId ${record.dig("contextMap","traceId")}
    spanId ${record.dig("contextMap","spanId")}
    service ${record["loggerName"]}
  </record>
</filter>

# Ship to Elasticsearch
<match equitycart.logs>
  @type elasticsearch
  host elasticsearch
  port 9200
  scheme http
  logstash_format true
  logstash_prefix equitycart-logs
  include_tag_key true
  tag_key @log_name
  reconnect_on_error true
  reload_connections false
  request_timeout 15s
</match>